export { default as Navbar } from './Navbar'
export { default as About } from './About'
export { default as Pricing } from './Pricing'
export { default as Contact } from './Contact'
export { default as NewNavbar } from './NewNavbar'
export { default as Footer } from './Footer'
